# Generated by Django 5.0.2 on 2024-02-13 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenancie',
            name='tenant',
        ),
        migrations.RenameModel(
            old_name='Tenancy',
            new_name='Tenancie',
        ),
        migrations.CreateModel(
            name='Tenan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Tenan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='tenancie',
            name='tenan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tenan'),
        ),
        migrations.DeleteModel(
            name='Tenant',
        ),
    ]
