# Generated by Django 5.0.2 on 2024-02-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_propertypicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='max_no_of_tenants',
            field=models.IntegerField(default=1),
        ),
    ]
