# Generated by Django 5.0.2 on 2024-02-13 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_tenancy_move_in_alter_owner_user_alter_searcher_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenancy',
            name='move_in',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
