# Generated by Django 5.0.2 on 2024-02-13 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_tenancy_move_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenancy',
            name='move_in',
        ),
    ]
