# Generated by Django 5.0.2 on 2024-02-13 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_tenant_user_delete_tenancy_delete_tenant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Renter',
        ),
    ]
